### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by fegerar** [dunkz0ne/website#51]
# Backend

- [x] **User join Dunk Zone**
- [x] **User login Dunk Zone**
- [x] **User Sign up**
- [x] **User sign in**
- [x] **Team selection**
- [x] **Click Team icon**
- [x] **Click Matches icon**
- [x] **Click News icon**
- [x] **Click League icon**
- [x] **Click Shop icon**
- [x] **User can access his dashboard**
- [x] **Admin can access his dashboard**
- [x] **User can become a journalist**
- [x] **Team create an official release**
- [x] **Journalist can publish an article**
- [x] **Click Player icon**
- [x] **User can change his name from his dashboard**
- [ ] **User can change his email from his dashboard**
- [ ] **User can change his password from his dashboard**
- [x] **User can change his team from his dashboard**
- [x] **User can change his bio from his dashboard**
- [x] **User can create a comment**
- [x] **User can put a like on a comment**
- [x] **User can comment a comment**
- [x] **User can save a comment**
- [x] **User can save an article**
- [x] **User can comment articles**
- [x] **User can put likes on comments**
- [x] **User can view all player details**
- [x] **Team delete an official release**
- [x] **Team change an official release**
- [x] **Admin can kick Users**
- [x] **Admin can delete a comment from an article**
- [x] **Admin can delete an article**
- [x] **Admin can increase the number of strikes**
- [x] **Admin can decrease the number of strikes**
- [x] **Admin can accept a user request as a new journalist**
- [x] **Admin can refuse a user request as a new journalist**
- [x] **Journalist can save a draft**
- [x] **Journalist can edit drafts**
- [x] **Journalist can delete a draft**
- [x] **Journalist can post drafts**
- [x] **Journalist can remove articles**

# Frontend

- [x] Matches
- [x] Matches details
- [x] News
- [x] Article
- [x] League
- [x] Admin Dashboard
- [x] Journalist Dashboard
- [x] User Dashboard
- [x] Team Manager 
- [x] Register

# Test

- [x] Fare i test

# Documentazione

- [ ] Diagramma ER
